completed map.go
lordvidex/gostream pull request #23
Opened 2024-12-12 21:59 UTC by Joshdike

2024-12-12 22:43 UTC, lordvidex commented on internal/db/inmemory/map.go
> +	}
Here you checked if m.data != nil, I suggest you create a helper function that automatically recreates the map when it's `nil` and access this everytime.

```go
func (m *Map[K, V]) safedata() map[K]V {
 if m.data == nil {
  m.data = make(map[K]V)
 }
 return m.data
}
```

Then everywhere you need access to the map, you call it using `m.safedata()`

2024-12-12 22:44 UTC, lordvidex commented on internal/db/inmemory/map.go
> +	}
Instead of ranging the map, you can simply return in constant time by doing
```go
value, ok := m.safedata()[k]
return value, ok
```

2024-12-12 22:56 UTC, lordvidex commented on internal/db/inmemory/map.go
> +	return values
Iterating a map with range does not guarantee the order in which values are returned. i.e. if you call `Snapshot` twice, you won't get the same list of values in the correct order. 

A `list.List` can maintain the insertion order of items and `Snapshot` can be generated in linear time. For example:

```go
import "container/list"
...

type M struct {
...
 order list.List[K]
}
...
func (m *M) Add(k, v) {
    m.Lock()
    defer m.Unlock()
    m.safedata()[k] = v
    m.order.PushBack(k)
}

func (m *M) Snapshot() []V {
    arr := make([]V, 0, len(m.data))
    // range over iter and add items into arr
}

func (m *M) Iter() iter.Seq[V] {
     return func(yield func(V) bool) {
       m.mu.RLock()
       defer m.mu.RUnlock()
       
       for it := m.order.Front(); it != nil; it = it.Next() {
             if ! yield(m.safedata()[it.Value()]) {
                 return
            }
       }
     }
}
```

2024-12-12 22:56 UTC, lordvidex requested changes
Added some review comments

2024-12-12 22:58 UTC, lordvidex commented on internal/db/inmemory/map.go
> +	return values
I wrote this offhand, so it's not syntactically correct, for example, list.List doesn't use generics yet, but I hope you get the idea I'm passing across.

2024-12-13 01:06 UTC, lordvidex commented on internal/db/inmemory/array_test.go
> +}
need to remove. this will break `ci`

2024-12-13 01:12 UTC, Joshdike commented on internal/db/inmemory/array_test.go
> +}
done

2024-12-13 01:13 UTC, merged